### ISSUE TITLE
Using DropKick with form validation.

### ISSUE THREAD

**Issue by benlevywebdesign** [Robdel12/DropKick#313]
Is it possible to use DropKick with form validation. See the [form on my website](http://benlevywebdesign.com/aaudining/#projectrequest) where I have two select elements. Without using dropkick they would normally get validated. I am using [jqueryvalidation](http://jqueryvalidation.org/) to do my validation.

**Comment by wwilsman** [comment]
Hey Ben,

By default, Dropkick hides original select elements with `display: none`. There's an option for `.validate()` called `ignore` which defaults to `":hidden"`. This means that it is ignoring the original select elements, and since Dropkick isn't a normal form control, no validation is being performed on them.

You have 2 possible solutions:

**Comment by benlevywebdesign** [comment]
This what I ended up doing and it works as should!

`ignore: {`
`hidden:"not(.selectoptions)",`
`hidden:"not(textarea.tinymce)"`
`},`

I added tinymce so that is why you see I added `textarea.tinymce` to the do not ignore option.

Thanks!
